#include "input/ge_key_codes.hpp"

#include <GLFW/glfw3.h>

using namespace GE;

Keys::Keys() :
    m_glfw_to_ge({
      { GLFW_KEY_SPACE, KeyCode::SPACE },
      { GLFW_KEY_APOSTROPHE, KeyCode::APOSTROPHE },
      { GLFW_KEY_COMMA, KeyCode::COMMA },
      { GLFW_KEY_MINUS, KeyCode::MINUS },
      { GLFW_KEY_PERIOD, KeyCode::PERIOD },
      { GLFW_KEY_SLASH, KeyCode::SLASH },
      { GLFW_KEY_0, KeyCode::D0 },
      { GLFW_KEY_1, KeyCode::D1 },
      { GLFW_KEY_2, KeyCode::D2 },
      { GLFW_KEY_3, KeyCode::D3 },
      { GLFW_KEY_4, KeyCode::D4 },
      { GLFW_KEY_5, KeyCode::D5 },
      { GLFW_KEY_6, KeyCode::D6 },
      { GLFW_KEY_7, KeyCode::D7 },
      { GLFW_KEY_8, KeyCode::D8 },
      { GLFW_KEY_9, KeyCode::D9 },
      { GLFW_KEY_SEMICOLON, KeyCode::SEMICOLON },
      { GLFW_KEY_EQUAL, KeyCode::EQUAL },
      { GLFW_KEY_A, KeyCode::A },
      { GLFW_KEY_B, KeyCode::B },
      { GLFW_KEY_C, KeyCode::C },
      { GLFW_KEY_D, KeyCode::D },
      { GLFW_KEY_E, KeyCode::E },
      { GLFW_KEY_F, KeyCode::F },
      { GLFW_KEY_G, KeyCode::G },
      { GLFW_KEY_H, KeyCode::H },
      { GLFW_KEY_I, KeyCode::I },
      { GLFW_KEY_J, KeyCode::J },
      { GLFW_KEY_K, KeyCode::K },
      { GLFW_KEY_L, KeyCode::L },
      { GLFW_KEY_M, KeyCode::M },
      { GLFW_KEY_N, KeyCode::N },
      { GLFW_KEY_O, KeyCode::O },
      { GLFW_KEY_P, KeyCode::P },
      { GLFW_KEY_Q, KeyCode::Q },
      { GLFW_KEY_R, KeyCode::R },
      { GLFW_KEY_S, KeyCode::S },
      { GLFW_KEY_T, KeyCode::T },
      { GLFW_KEY_U, KeyCode::U },
      { GLFW_KEY_V, KeyCode::V },
      { GLFW_KEY_W, KeyCode::W },
      { GLFW_KEY_X, KeyCode::X },
      { GLFW_KEY_Y, KeyCode::Y },
      { GLFW_KEY_Z, KeyCode::Z },
      { GLFW_KEY_LEFT_BRACKET, KeyCode::LEFT_BRACKET },
      { GLFW_KEY_BACKSLASH, KeyCode::BACKSLASH },
      { GLFW_KEY_RIGHT_BRACKET, KeyCode::RIGHT_BRACKET },
      { GLFW_KEY_GRAVE_ACCENT, KeyCode::GRAVE_ACCENT },
      { GLFW_KEY_ESCAPE, KeyCode::ESCAPE },
      { GLFW_KEY_ENTER, KeyCode::ENTER },
      { GLFW_KEY_TAB, KeyCode::TAB },
      { GLFW_KEY_BACKSPACE, KeyCode::BACKSPACE },
      { GLFW_KEY_INSERT, KeyCode::INSERT },
      { GLFW_KEY_DELETE, KeyCode::DELETE },
      { GLFW_KEY_RIGHT, KeyCode::RIGHT },
      { GLFW_KEY_LEFT, KeyCode::LEFT },
      { GLFW_KEY_DOWN, KeyCode::DOWN },
      { GLFW_KEY_UP, KeyCode::UP },
      { GLFW_KEY_PAGE_UP, KeyCode::PAGE_UP },
      { GLFW_KEY_PAGE_DOWN, KeyCode::PAGE_DOWN },
      { GLFW_KEY_HOME, KeyCode::HOME },
      { GLFW_KEY_END, KeyCode::END },
      { GLFW_KEY_CAPS_LOCK, KeyCode::CAPS_LOCK },
      { GLFW_KEY_SCROLL_LOCK, KeyCode::SCROLL_LOCK },
      { GLFW_KEY_NUM_LOCK, KeyCode::NUM_LOCK },
      { GLFW_KEY_PRINT_SCREEN, KeyCode::PRINT_SCREEN },
      { GLFW_KEY_PAUSE, KeyCode::PAUSE },
      { GLFW_KEY_F1, KeyCode::F1 },
      { GLFW_KEY_F2, KeyCode::F2 },
      { GLFW_KEY_F3, KeyCode::F3 },
      { GLFW_KEY_F4, KeyCode::F4 },
      { GLFW_KEY_F5, KeyCode::F5 },
      { GLFW_KEY_F6, KeyCode::F6 },
      { GLFW_KEY_F7, KeyCode::F7 },
      { GLFW_KEY_F8, KeyCode::F8 },
      { GLFW_KEY_F9, KeyCode::F9 },
      { GLFW_KEY_F10, KeyCode::F10 },
      { GLFW_KEY_F11, KeyCode::F11 },
      { GLFW_KEY_F12, KeyCode::F12 },
      { GLFW_KEY_F13, KeyCode::F13 },
      { GLFW_KEY_F14, KeyCode::F14 },
      { GLFW_KEY_F15, KeyCode::F15 },
      { GLFW_KEY_F16, KeyCode::F16 },
      { GLFW_KEY_F17, KeyCode::F17 },
      { GLFW_KEY_F18, KeyCode::F18 },
      { GLFW_KEY_F19, KeyCode::F19 },
      { GLFW_KEY_F20, KeyCode::F20 },
      { GLFW_KEY_F21, KeyCode::F21 },
      { GLFW_KEY_F22, KeyCode::F22 },
      { GLFW_KEY_F23, KeyCode::F23 },
      { GLFW_KEY_F24, KeyCode::F24 },
      { GLFW_KEY_F25, KeyCode::F25 },
      { GLFW_KEY_KP_0, KeyCode::KP_0 },
      { GLFW_KEY_KP_1, KeyCode::KP_1 },
      { GLFW_KEY_KP_2, KeyCode::KP_2 },
      { GLFW_KEY_KP_3, KeyCode::KP_3 },
      { GLFW_KEY_KP_4, KeyCode::KP_4 },
      { GLFW_KEY_KP_5, KeyCode::KP_5 },
      { GLFW_KEY_KP_6, KeyCode::KP_6 },
      { GLFW_KEY_KP_7, KeyCode::KP_7 },
      { GLFW_KEY_KP_8, KeyCode::KP_8 },
      { GLFW_KEY_KP_9, KeyCode::KP_9 },
      { GLFW_KEY_KP_DECIMAL, KeyCode::KP_DECIMAL },
      { GLFW_KEY_KP_DIVIDE, KeyCode::KP_DIVIDE },
      { GLFW_KEY_KP_MULTIPLY, KeyCode::KP_MULTIPLY },
      { GLFW_KEY_KP_SUBTRACT, KeyCode::KP_SUBTRACT },
      { GLFW_KEY_KP_ADD, KeyCode::KP_ADD },
      { GLFW_KEY_KP_ENTER, KeyCode::KP_ENTER },
      { GLFW_KEY_KP_EQUAL, KeyCode::KP_EQUAL },
      { GLFW_KEY_LEFT_SHIFT, KeyCode::LEFT_SHIFT },
      { GLFW_KEY_LEFT_CONTROL, KeyCode::LEFT_CONTROL },
      { GLFW_KEY_LEFT_ALT, KeyCode::LEFT_ALT },
      { GLFW_KEY_LEFT_SUPER, KeyCode::LEFT_SUPER },
      { GLFW_KEY_RIGHT_SHIFT, KeyCode::RIGHT_SHIFT },
      { GLFW_KEY_RIGHT_CONTROL, KeyCode::RIGHT_CONTROL },
      { GLFW_KEY_RIGHT_ALT, KeyCode::RIGHT_ALT },
      { GLFW_KEY_RIGHT_SUPER, KeyCode::RIGHT_SUPER },
      { GLFW_KEY_MENU, KeyCode::MENU },
      { GLFW_MOUSE_BUTTON_1, KeyCode::MOUSE_BT_LEFT },
      { GLFW_MOUSE_BUTTON_2, KeyCode::MOUSE_BT_RIGHT },
      { GLFW_MOUSE_BUTTON_3, KeyCode::MOUSE_BT_MIDDLE },
      { GLFW_KEY_UNKNOWN, KeyCode::NONE },
    }),
    m_ge_to_glfw({
      { KeyCode::SPACE, GLFW_KEY_SPACE },
      { KeyCode::APOSTROPHE, GLFW_KEY_APOSTROPHE },
      { KeyCode::COMMA, GLFW_KEY_COMMA },
      { KeyCode::MINUS, GLFW_KEY_MINUS },
      { KeyCode::PERIOD, GLFW_KEY_PERIOD },
      { KeyCode::SLASH, GLFW_KEY_SLASH },
      { KeyCode::D0, GLFW_KEY_0 },
      { KeyCode::D1, GLFW_KEY_1 },
      { KeyCode::D2, GLFW_KEY_2 },
      { KeyCode::D3, GLFW_KEY_3 },
      { KeyCode::D4, GLFW_KEY_4 },
      { KeyCode::D5, GLFW_KEY_5 },
      { KeyCode::D6, GLFW_KEY_6 },
      { KeyCode::D7, GLFW_KEY_7 },
      { KeyCode::D8, GLFW_KEY_8 },
      { KeyCode::D9, GLFW_KEY_9 },
      { KeyCode::SEMICOLON, GLFW_KEY_SEMICOLON },
      { KeyCode::EQUAL, GLFW_KEY_EQUAL },
      { KeyCode::A, GLFW_KEY_A },
      { KeyCode::B, GLFW_KEY_B },
      { KeyCode::C, GLFW_KEY_C },
      { KeyCode::D, GLFW_KEY_D },
      { KeyCode::E, GLFW_KEY_E },
      { KeyCode::F, GLFW_KEY_F },
      { KeyCode::G, GLFW_KEY_G },
      { KeyCode::H, GLFW_KEY_H },
      { KeyCode::I, GLFW_KEY_I },
      { KeyCode::J, GLFW_KEY_J },
      { KeyCode::K, GLFW_KEY_K },
      { KeyCode::L, GLFW_KEY_L },
      { KeyCode::M, GLFW_KEY_M },
      { KeyCode::N, GLFW_KEY_N },
      { KeyCode::O, GLFW_KEY_O },
      { KeyCode::P, GLFW_KEY_P },
      { KeyCode::Q, GLFW_KEY_Q },
      { KeyCode::R, GLFW_KEY_R },
      { KeyCode::S, GLFW_KEY_S },
      { KeyCode::T, GLFW_KEY_T },
      { KeyCode::U, GLFW_KEY_U },
      { KeyCode::V, GLFW_KEY_V },
      { KeyCode::W, GLFW_KEY_W },
      { KeyCode::X, GLFW_KEY_X },
      { KeyCode::Y, GLFW_KEY_Y },
      { KeyCode::Z, GLFW_KEY_Z },
      { KeyCode::LEFT_BRACKET, GLFW_KEY_LEFT_BRACKET },
      { KeyCode::BACKSLASH, GLFW_KEY_BACKSLASH },
      { KeyCode::RIGHT_BRACKET, GLFW_KEY_RIGHT_BRACKET },
      { KeyCode::GRAVE_ACCENT, GLFW_KEY_GRAVE_ACCENT },
      { KeyCode::ESCAPE, GLFW_KEY_ESCAPE },
      { KeyCode::ENTER, GLFW_KEY_ENTER },
      { KeyCode::TAB, GLFW_KEY_TAB },
      { KeyCode::BACKSPACE, GLFW_KEY_BACKSPACE },
      { KeyCode::INSERT, GLFW_KEY_INSERT },
      { KeyCode::DELETE, GLFW_KEY_DELETE },
      { KeyCode::RIGHT, GLFW_KEY_RIGHT },
      { KeyCode::LEFT, GLFW_KEY_LEFT },
      { KeyCode::DOWN, GLFW_KEY_DOWN },
      { KeyCode::UP, GLFW_KEY_UP },
      { KeyCode::PAGE_UP, GLFW_KEY_PAGE_UP },
      { KeyCode::PAGE_DOWN, GLFW_KEY_PAGE_DOWN },
      { KeyCode::HOME, GLFW_KEY_HOME },
      { KeyCode::END, GLFW_KEY_END },
      { KeyCode::CAPS_LOCK, GLFW_KEY_CAPS_LOCK },
      { KeyCode::SCROLL_LOCK, GLFW_KEY_SCROLL_LOCK },
      { KeyCode::NUM_LOCK, GLFW_KEY_NUM_LOCK },
      { KeyCode::PRINT_SCREEN, GLFW_KEY_PRINT_SCREEN },
      { KeyCode::PAUSE, GLFW_KEY_PAUSE },
      { KeyCode::F1, GLFW_KEY_F1 },
      { KeyCode::F2, GLFW_KEY_F2 },
      { KeyCode::F3, GLFW_KEY_F3 },
      { KeyCode::F4, GLFW_KEY_F4 },
      { KeyCode::F5, GLFW_KEY_F5 },
      { KeyCode::F6, GLFW_KEY_F6 },
      { KeyCode::F7, GLFW_KEY_F7 },
      { KeyCode::F8, GLFW_KEY_F8 },
      { KeyCode::F9, GLFW_KEY_F9 },
      { KeyCode::F10, GLFW_KEY_F10 },
      { KeyCode::F11, GLFW_KEY_F11 },
      { KeyCode::F12, GLFW_KEY_F12 },
      { KeyCode::F13, GLFW_KEY_F13 },
      { KeyCode::F14, GLFW_KEY_F14 },
      { KeyCode::F15, GLFW_KEY_F15 },
      { KeyCode::F16, GLFW_KEY_F16 },
      { KeyCode::F17, GLFW_KEY_F17 },
      { KeyCode::F18, GLFW_KEY_F18 },
      { KeyCode::F19, GLFW_KEY_F19 },
      { KeyCode::F20, GLFW_KEY_F20 },
      { KeyCode::F21, GLFW_KEY_F21 },
      { KeyCode::F22, GLFW_KEY_F22 },
      { KeyCode::F23, GLFW_KEY_F23 },
      { KeyCode::F24, GLFW_KEY_F24 },
      { KeyCode::F25, GLFW_KEY_F25 },
      { KeyCode::KP_0, GLFW_KEY_KP_0 },
      { KeyCode::KP_1, GLFW_KEY_KP_1 },
      { KeyCode::KP_2, GLFW_KEY_KP_2 },
      { KeyCode::KP_3, GLFW_KEY_KP_3 },
      { KeyCode::KP_4, GLFW_KEY_KP_4 },
      { KeyCode::KP_5, GLFW_KEY_KP_5 },
      { KeyCode::KP_6, GLFW_KEY_KP_6 },
      { KeyCode::KP_7, GLFW_KEY_KP_7 },
      { KeyCode::KP_8, GLFW_KEY_KP_8 },
      { KeyCode::KP_9, GLFW_KEY_KP_9 },
      { KeyCode::KP_DECIMAL, GLFW_KEY_KP_DECIMAL },
      { KeyCode::KP_DIVIDE, GLFW_KEY_KP_DIVIDE },
      { KeyCode::KP_MULTIPLY, GLFW_KEY_KP_MULTIPLY },
      { KeyCode::KP_SUBTRACT, GLFW_KEY_KP_SUBTRACT },
      { KeyCode::KP_ADD, GLFW_KEY_KP_ADD },
      { KeyCode::KP_ENTER, GLFW_KEY_KP_ENTER },
      { KeyCode::KP_EQUAL, GLFW_KEY_KP_EQUAL },
      { KeyCode::LEFT_SHIFT, GLFW_KEY_LEFT_SHIFT },
      { KeyCode::LEFT_CONTROL, GLFW_KEY_LEFT_CONTROL },
      { KeyCode::LEFT_ALT, GLFW_KEY_LEFT_ALT },
      { KeyCode::LEFT_SUPER, GLFW_KEY_LEFT_SUPER },
      { KeyCode::RIGHT_SHIFT, GLFW_KEY_RIGHT_SHIFT },
      { KeyCode::RIGHT_CONTROL, GLFW_KEY_RIGHT_CONTROL },
      { KeyCode::RIGHT_ALT, GLFW_KEY_RIGHT_ALT },
      { KeyCode::RIGHT_SUPER, GLFW_KEY_RIGHT_SUPER },
      { KeyCode::MENU, GLFW_KEY_MENU },
      { KeyCode::MOUSE_BT_LEFT, GLFW_MOUSE_BUTTON_1 },
      { KeyCode::MOUSE_BT_RIGHT, GLFW_MOUSE_BUTTON_2 },
      { KeyCode::MOUSE_BT_MIDDLE, GLFW_MOUSE_BUTTON_3 },
      { KeyCode::NONE, GLFW_KEY_UNKNOWN },
    })
{
}

KeyCode GE::Keys::ConvertGLFWtoGE(i32 code)
{
  return Get().m_glfw_to_ge.at(code);
}

i32 GE::Keys::ConvertGEtoGFLW(KeyCode code)
{
  return Get().m_ge_to_glfw.at(code);
}

Keys& Keys::Get()
{
  static Keys keys{};
  return keys;
}
